### ISSUE TITLE
How is the information saved?

### ISSUE THREAD

**Issue by metafory** [nimeshnayaju/tldrawe#3]
Hi!

Amazing implementation of tldraw.
Are you persisting the tldraw overlay for the specific URL with liveblocks?
otherwise - how is the overlay saved for reuse?

**Comment by T017** [comment]
I have the same question :)

**Comment by nimeshnayaju** [comment]
Hey, all contents of a page are stored locally in session storage, and the data is automatically cleared once the page session ends. Here's a [link to the MDN documentation on Session Storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) if you'd like to learn more.
