### ISSUE TITLE
This project seems to be currently broken

### ISSUE THREAD

**Issue by kolibril13** [nimeshnayaju/tldrawe#4]
Hi @nimeshnayaju , thanks for making this project!
I'd love to use this tldraw overlay, however after installing it from the chrome store, I was not able to activate the overlay.
Pressing the "Toggle Overlay" button simply does nothing.
Are you planning support for the most recent tldraw version and the most recent google chrome? 
That would be really great to have!

**Comment by nimeshnayaju** [comment]
Hey, I am no longer maintaining the project and I have not been keeping up with tldraw updates. Sorry about the inconvenience.
